apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-multitool
  labels:
    app: nginx-multitool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-multitool
  template:
    metadata:
      labels:
        app: nginx-multitool
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          name: http
      - name: multitool
        image: wbitt/network-multitool:latest
        ports:
        - containerPort: 8080
          name: http-alt
        env:
        - name: HTTP_PORT
          value: "8080"

