apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-init-demo
  labels:
    app: nginx-init
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-init
  template:
    metadata:
      labels:
        app: nginx-init
    spec:
      initContainers:
      - name: init-wait-service
        image: busybox:1.28
        command: ['sh', '-c', 'until nslookup nginx-init-svc.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for nginx-init-svc; sleep 2; done']
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

